name: shell commands

on: [push]

jobs:
    run-github-action:
        runs-on: ubuntu-latest
        steps:
            - name: Simple JS Action
              id: greet
              uses: actions/hello-world-javascript-action@v1
              with: 
                who-to-greet: Ibrahim Olayinka
            - name: Log greeting time
              run: |
                echo "${{steps.greet.outputs.time}}"
            - name: push a random file
              run: |
                pwd
                ls -a
                git init
                git remote add origin "https://$GITHUB_ACTORS:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git config --global user.email "ibrahimolayinkaa@gmail.com"
                git config --global user.name "Olayinka ibrahim"
                git fetch
                git checkout master
                git branch --set-upstream-to=origin/master
                git pull
                ls -a
                echo $RANDOM >> random.txt
                ls -a
                git add -A
                git commit -m "Random file"
                git push
    
 