name: shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello world"
      - name: multi-line script
        run: |
            node -v
            npm -v
