name: shell commands

on: 
    repository_dispatch:
        types: [build]
    # push:

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: client payload
              run: |
                echo "${{github.event.client_payload.env}}"
            - name: echo string
              run: echo "Hello world"
            - name: multi-line script
              run: |
                node -v
                npm -v
                echo "${{secrets.github_action}}"
            - name: decrypt file
              env:
                PASSPHRASE: ${{secrets.PASSPHRASE}}
                JOBCONTEXT: ${{toJson(job)}}
                RUNNERCONTEXT: ${{toJson(runner)}}
                STEPSCONTEXT: ${{toJson(steps)}}
              run: |
                gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json encrypted-file.gpg
                cat $HOME/secret.json
                echo $JOBCONTEXT

    run-on-window:
        runs-on: windows-latest
        needs: ["run-shell-commands"]
        steps:
            - name: Directory Powershell
              run: Get-Location
            - name: Directory Bash
              run: pwd
              shell: bash
